# Draft - Aircraft Types
- Aircraft data in january 2023 (no specific dates)
- Flight schedule data 

They both have in common the airline iata code, but there are no dates related to when was an specific model used (only that the data is from January 2023). 

Possibilities of merging:
- most popular aircraft used within an airline in January
- calculate most frequent airline in January for a specific route (BRU-MAD)
- match the aircraft to the route frequent airline
- calculate passengers based on aircraft model

In [36]:
import pandas as pd
import os
import sys
from pathlib import Path

In [2]:
# Add the base path to sys.path
BASE_DIR = Path().resolve().parent
sys.path.append(str(BASE_DIR / 'core'))

# Define the path to load the file
file_path_jan = os.path.join("..", "data", "aircraft", "aircraft-database-complete-2023-01.csv")
file_path_database = os.path.join("..", "data", "aircraft", "aircraftDatabase.csv")
file_path_schedule = os.path.join("..", "data", "df_schedule_no_changes.csv")

# Load the DataFrame
df_2023_01 = pd.read_csv(file_path_jan, encoding='latin1', dtype={7: str})
df_aircraftDatabase = pd.read_csv(file_path_database, encoding='latin1', dtype={7: str})
df_schedule = pd.read_csv(file_path_schedule)
print("DataFrames loaded successfully")

DataFrames loaded successfully

In [3]:
# Get the column names of df_aircraftDatabase
aircraft_columns = df_aircraftDatabase.columns

# Extract the first 14 and the last column names from df_aircraftDatabase
new_column_names = list(aircraft_columns[:14]) + [aircraft_columns[-1]]

# Rename columns in df_2023_01_cleaned
df_2023_01.columns = new_column_names
df_2023_01_cleaned = df_2023_01.dropna(subset=['registration'])


df_comparison = df_2023_01_cleaned.copy()
df_comparison = df_comparison.dropna(subset=['operatoriata'])

# Convert all characters in the 'operator' column to uppercase
df_comparison['operator'] = df_comparison['operator'].str.upper()
df_comparison

,icao24,registration,manufacturericao,manufacturername,model,typecode,serialnumber,linenumber,icaoaircrafttype,operator,operatorcallsign,operatoricao,operatoriata,owner,categoryDescription
129,004001,Z-WTV,ILYUSHIN,Ilyushin,Il-76T,IL76,073410279,0710,L4J,AVIENT AVIATION,AVAVIA,SMJ,Z3,Avient,NaN
134,004013,Z-FJF,NaN,NaN,Embraer ERJ-145LU,E145,NaN,NaN,NaN,FASTJET ZIMBABWE,NaN,FJW,FN,NaN,NaN
136,00401f,Z-ALT,MCDONNELL DOUGLAS,Mcdonnell Douglas,DC-10-30 /F,DC10,47818,305,L3J,AVIENT AVIATION,AVAVIA,SMJ,Z3,NaN,NaN
137,004020,Z-ALB,MCDONNELL DOUGLAS,Douglas,DC-8-62AF,DC86,46162,555,L4J,AVIENT AVIATION,AVAVIA,SMJ,Z3,NaN,NaN
140,004028,Z-FJG,NaN,NaN,Embraer ERJ-145MP,E145,NaN,NaN,NaN,FASTJET ZIMBABWE,NaN,FJW,FN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549325,e8c096,OB2181P,NaN,NaN,Boeing 737-3H4,B733,NaN,NaN,NaN,STAR PERU,NaN,SRU,2I,NaN,NaN
549383,e94073,CP-3142,NaN,NaN,Embraer E190LR,E190,NaN,NaN,NaN,AMASZONAS,NaN,AZN,Z8,NaN,NaN
549384,e94074,CP-3145,NaN,NaN,Embraer E190LR,E190,NaN,NaN,NaN,AMASZONAS,NaN,AZN,Z8,NaN,NaN
549426,e94c42,CP-3138,NaN,NaN,Boeing 737-8Q8,B738,NaN,NaN,NaN,BOLIVIANA DE AVIACION,NaN,BOV,OB,NaN,NaN
549427,e94c4f,CP-3151,NaN,NaN,Boeing 737-8Q8,B738,NaN,NaN,NaN,BOLIVIANA DE AVIACION,NaN,BOV,OB,NaN,NaN

In [4]:
df_schedule_compare = df_schedule.copy()
df_schedule_compare = df_schedule_compare.dropna(subset=['airline_iata_code'])

# Extract unique values from both columns
unique_operatoriata = df_comparison['operatoriata'].unique()
unique_airline_iata_code = df_schedule_compare['airline_iata_code'].unique()

# Find matching values between the two lists
matching_values = set(unique_operatoriata).intersection(unique_airline_iata_code)

# Count the number of matching values
matching_count = len(matching_values)

# Print the result
print(f'Number of unique operator IATA: {len(unique_operatoriata)}')
print(f'Number of unique airline IATA: {len(unique_airline_iata_code)}')
print(f'Number of matching unique values: {matching_count}')
print(matching_values)

Number of unique operator IATA: 728
Number of unique airline IATA: 191
Number of matching unique values: 162
{'FR', 'BA', 'IB', 'AT', 'EK', 'QR', 'A2', 'V0', 'FH', 'TB', 'DC', 'T3', 'BT', 'KM', 'OZ', 'X9', 'BG', 'MS', 'OS', 'ZP', 'RO', '4Y', 'H5', 'OU', 'OJ', 'IS', 'WG', '7A', '7W', 'GB', 'EW', 'TE', 'LH', 'UX', 'NH', 'FB', 'PY', 'JU', 'SV', 'LX', 'G9', '8W', 'AY', 'TK', 'EN', 'BU', 'BO', 'M2', 'ME', '5X', 'EY', 'P8', 'PU', 'CE', 'SK', 'EZ', 'WF', 'MP', 'H7', 'XC', 'LS', 'E4', 'EI', 'W8', 'AZ', '4O', 'HU', 'PP', 'VY', 'XM', 'HV', '3S', 'WB', 'WT', 'J4', 'SN', '1I', 'TW', 'E9', 'UA', 'MV', 'CC', 'AP', '6H', 'AC', 'PC', 'AG', 'I2', 'HN', 'DB', 'FI', '7L', 'B5', 'AH', 'MT', '2L', 'KL', 'MB', 'TX', 'P4', '1T', 'EE', 'HG', 'ZQ', 'GQ', '5K', '5F', 'BN', 'NO', 'J2', 'KK', 'DE', 'RJ', '3U', 'LG', 'X3', 'V3', 'SQ', 'FS', 'TU', 'TG', 'C3', 'QY', 'AR', 'ET', 'GT', 'QS', '3O', 'JP', 'K4', 'DX', 'P6', 'FX', 'LW', 'TP', 'WK', 'N8', 'LO', 'LY', 'HT', 'XY', 'M6', 'R5', 'RS', '6Y', 'WX', 'A9', 'QE', 'RE', 'D0', 'PQ', 'HY', 'TS', 'AF', 'ED', 'XQ', 'A3', 'KE', 'U2', 'DL', 'BJ', 'HR'}

In [20]:
df_schedule_compare

,uuid,route_iata_code,type,status,dep_iata_code,dep_delay,sdt,adt,arr_iata_code,sat,aat,airline_name,cargo,private,airline_iata_code,flight_iata_number,calc_sft,calc_aft,calc_flight_distance_km
0,D4B953A52B6B376A144AFA95DBCF5C14D7154C83,BRU-CPH,ARRIVAL,LANDED,BRU,12.0,2023-08-15 14:00:00+00:00,2023-08-15 14:12:00+00:00,CPH,2023-08-15 15:30:00+00:00,2023-08-15 15:17:00+00:00,SAS,False,False,SK,SK1594,90.0,65.0,754.4
1,476BC61CB63C6766B18F9AF8AF60D3A8F66FF08C,OUD-BRU,ARRIVAL,LANDED,OUD,10.0,2023-08-15 14:00:00+00:00,2023-08-15 14:10:00+00:00,BRU,2023-08-15 16:55:00+00:00,2023-08-15 16:43:00+00:00,ROYAL AIR MAROC,False,False,AT,AT1688,175.0,153.0,1864.7
2,412CDB45D7CC4CF4C637C50D443E4649773C1787,BRU-CPH,DEPARTURE,ACTIVE,BRU,12.0,2023-08-15 14:00:00+00:00,2023-08-15 14:12:00+00:00,CPH,2023-08-15 15:30:00+00:00,2023-08-15 15:42:00+00:00,SAS,False,False,SK,SK1594,90.0,90.0,754.4
3,01549CD997A261C77CD8CDE664172687D13255BF,IBZ-BRU,ARRIVAL,LANDED,IBZ,23.0,2023-08-15 14:05:00+00:00,2023-08-15 14:27:00+00:00,BRU,2023-08-15 16:20:00+00:00,2023-08-15 16:22:00+00:00,BRUSSELS AIRLINES,False,False,SN,SN3778,135.0,115.0,1359.5
4,8CBE8A849C7510077FA66B228920701423E8C976,OTP-BRU,ARRIVAL,SCHEDULED,OTP,90.0,2023-08-15 14:05:00+00:00,2023-08-15 15:34:00+00:00,BRU,2023-08-15 16:55:00+00:00,2023-08-15 18:25:00+00:00,TAROM,False,False,RO,RO373,170.0,171.0,1754.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340293,5BFEF3E39CACFCC7180DFAED2D5371C7DE423459,BRU-DJE,ARRIVAL,ACTIVE,BRU,20.0,2023-08-15 13:35:00+00:00,2023-08-15 13:54:00+00:00,DJE,2023-08-15 16:55:00+00:00,2023-08-15 17:15:00+00:00,TUIFLY,False,False,X3,X32705,200.0,201.0,1960.7
340294,83E13A7218F696B892BA520B29FF65919B0F58AC,BRU-TNG,ARRIVAL,LANDED,BRU,20.0,2023-08-15 13:40:00+00:00,2023-08-15 13:59:00+00:00,TNG,2023-08-15 17:05:00+00:00,2023-08-15 16:40:00+00:00,TUIFLY,False,False,X3,X32661,205.0,161.0,1881.2
340295,4ED24DBA03246DB7CBD3CB23AEA4EDE531119E08,BRU-LIN,ARRIVAL,LANDED,BRU,31.0,2023-08-15 13:45:00+00:00,2023-08-15 14:16:00+00:00,LIN,2023-08-15 15:10:00+00:00,2023-08-15 15:21:00+00:00,ITA AIRWAYS,False,False,AZ,AZ149,85.0,65.0,702.8
340296,98626013D1BB61DB09DBAAEDDC3C791F7BE82A66,BRU-BCN,ARRIVAL,LANDED,BRU,43.0,2023-08-15 13:50:00+00:00,2023-08-15 14:32:00+00:00,BCN,2023-08-15 15:55:00+00:00,2023-08-15 16:14:00+00:00,RYANAIR,False,False,FR,FR2917,125.0,102.0,1083.8
340297,1EE1DB36CE59DE05C02304CBAFBEC0C20E250207,BRU-GOT,ARRIVAL,LANDED,BRU,65.0,2023-08-15 13:55:00+00:00,2023-08-15 15:00:00+00:00,GOT,2023-08-15 15:35:00+00:00,2023-08-15 16:12:00+00:00,BRUSSELS AIRLINES,False,False,SN,SN2317,100.0,72.0,905.0

In [31]:
filtered_rows = df_comparison[df_comparison['operatoriata'] == 'IB']
filtered_rows

,icao24,registration,manufacturericao,manufacturername,model,typecode,serialnumber,linenumber,icaoaircrafttype,operator,operatorcallsign,operatoricao,operatoriata,owner,categoryDescription
28439,3414c7,EC-HQH,AIRBUS,Airbus,A340-313,A343,387,NaN,L4J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
28445,34150e,EC-IGK,AIRBUS,Airbus,A321-213,A321,1572,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
28466,34164c,EC-IQR,AIRBUS,Airbus,A340 642,A346,460,NaN,L4J,NaN,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
28470,341683,EC-ILO,AIRBUS,Airbus,A321-212,A321,1681,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
28489,3420ce,EC-JAZ,AIRBUS,Airbus,A319 111,A319,2264,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
28739,3430c4,EC-KOY,AIRBUS,Airbus,A319 111,A319,3443,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
28832,343315,EC-LEU,AIRBUS,Airbus,Airbus A340 642,A346,960,NaN,L4J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
28881,343488,EC-LCZ,AIRBUS,Airbus,A340 642,A346,993,NaN,L4J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29096,3442cb,EC-LRR,ATR,Avions De Transport Regional,ATR 72 600,AT76,1023,NaN,L2T,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
29106,344305,EC-LUK,AIRBUS,Airbus,Airbus A330-302,A333,1385,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
29197,344449,EC-LVD,AIRBUS,Airbus,A320-216,A320,5570,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
29370,3450d6,EC-MJA,AIRBUS,Airbus,A330 202,A332,1700,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,No ADS-B Emitter Category Information
29640,3455c1,EC-MSY,AIRBUS,Airbus,A330-202,A332,1835,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,Heavy (> 300000 lbs)
29648,3455d5,EC-MUD,NaN,NaN,A330-202,NaN,NaN,NaN,NaN,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,Heavy (> 300000 lbs)
29700,345691,EC-MXU,AIRBUS,NaN,NaN,A320-251N,NaN,NaN,NaN,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29701,345692,EC-MXY,AIRBUS,A320-251n,NaN,A20N,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29712,346045,EC-MYA,NaN,NaN,A330-202,NaN,NaN,NaN,NaN,LEVEL (IBERIA),IBERIA,IBE,IB,NaN,NaN
29715,34604b,EC-MVZ,NaN,NaN,Mitsubishi CRJ-1000,CRJX,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
29718,34604e,EC-MXV,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29721,346057,EC-MYX,NaN,NaN,Airbus A350-941,NaN,NaN,NaN,NaN,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29751,346146,EC-NBE,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29752,346147,EC-NCM,NaN,NaN,Airbus A320-251N,A20N,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
29774,346190,EC-NCD,NaN,NaN,ATR 72-600,AT76,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
29782,3461cb,EC-NCX,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29787,346204,EC-NDN,AIRBUS,Airbus Industrie,A320-251N,A20N,8939,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29796,34628d,EC-NDR,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29812,346303,EC-NER,AIRBUS,NaN,NaN,A20N,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29822,346316,EC-NFZ,AIRBUS,Airbus,A320-251N,A20N,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29842,346386,EC-NGT,AIRBUS,Airbus,A350-941,A359,366,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29861,34640e,EC-NIG,AIRBUS,Airbus,A350-941,A359,397,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29868,346419,EC-NIS,AIRBUS,Airbus Industrie,A350-941,A359,406,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29882,346456,EC-NJM,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29884,346458,EC-NJU,AIRBUS,Airbus Industrie,A320-251N,A20N,10065,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,Iberia,NaN
29897,346499,EC-NJY,AIRBUS,NaN,NaN,A320,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29924,346555,EC-NLP,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29932,34659a,EC-NMZ,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29944,346605,EC-NNH,AIRBUS,Airbus,A330-202,A332,1936,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
29947,34660b,EC-NTI,NaN,NaN,Airbus A320-251N,A20N,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
30005,347206,EC-NSC,AIRBUS,NaN,A350-941,A359,NaN,NaN,L2J,IBERIA AIRLINES,IBERIA,IBE,IB,NaN,NaN
30008,347219,EC-NTA,NaN,NaN,Airbus A320-251N,A20N,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
30014,347287,EC-NTO,NaN,NaN,Airbus A320-251N,A20N,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN
130162,4d23b6,9H-NFT,NaN,NaN,ATR 72-600,AT76,NaN,NaN,NaN,IBERIA,NaN,IBE,IB,NaN,NaN

In [32]:
model_counts = filtered_rows['model'].value_counts()
print(model_counts)

model
A350-941               11
Airbus A320-251N        4
A330-202                4
A320-251N               3
A340 642                2
ATR 72-600              2
A319 111                2
A340-313                1
A321-213                1
A320-216                1
Airbus A330-302         1
ATR 72 600              1
Airbus A340 642         1
A321-212                1
A330 202                1
Mitsubishi CRJ-1000     1
Airbus A350-941         1
Name: count, dtype: int64

In [35]:
import pandas as pd

# Filter for the route
route_df = df_schedule_compare[df_schedule_compare['route_iata_code'] == 'BRU-MAD'].copy()

# Ensure the flight date column is datetime and extract the month
route_df['month'] = pd.to_datetime(route_df['sdt']).dt.month

# Group by month
result = []
for month, group in route_df.groupby('month'):
    # Count the occurrences of each airline
    airline_counts = group['airline_iata_code'].value_counts()
    
    # Identify the most popular airline and its count
    most_popular = airline_counts.idxmax()
    most_popular_count = airline_counts.max()
    
    # Create a list of other airlines with their counts
    other_airlines_with_counts = [
        f"{airline} ({count})" 
        for airline, count in airline_counts.items() 
        if airline != most_popular
    ]
    
    # Append to the result
    result.append({
        'month': month,
        'most_popular_airline': most_popular,
        'most_popular_flight_count': most_popular_count,
        'other_airlines': other_airlines_with_counts
    })

# Create the final DataFrame
final_df = pd.DataFrame(result)

# Map months from numeric to names (optional)
final_df['month'] = final_df['month'].map({
    1: 'January', 2: 'February', 3: 'March', 4: 'April',
    5: 'May', 6: 'June', 7: 'July', 8: 'August',
    9: 'September', 10: 'October', 11: 'November', 12: 'December'
})

# Display the result
final_df

,month,most_popular_airline,most_popular_flight_count,other_airlines
0,January,IB,198,"[SN (116), E9 (76), FR (62), UX (46), NONE (4)..."
1,February,IB,184,"[SN (122), E9 (76), FR (56), AP (27), P6 (8), ..."
2,March,IB,198,"[SN (147), E9 (94), FR (61), UX (30), WT (4), ..."
3,April,IB,190,"[SN (151), E9 (108), FR (59), UX (12), WT (4)]"
4,May,IB,200,"[SN (159), E9 (77), FR (59), UX (42), AP (4), ..."
5,June,SN,183,"[IB (180), UX (120), FR (51)]"
6,July,IB,200,"[SN (187), UX (120), FR (59), NONE (2), AP (2)]"
7,August,IB,182,"[SN (162), UX (123), FR (54)]"
8,September,IB,188,"[SN (174), UX (120), FR (59)]"
9,October,IB,205,"[SN (189), UX (124), FR (61)]"
10,November,IB,191,"[SN (180), UX (119), FR (59), 6Y (2), X3 (2), ..."
11,December,IB,191,"[SN (157), UX (120), FR (53), NONE (4), D0 (4)]"